<%@page import="net.smartworks.model.work.FormField"%>
<%@page import="net.smartworks.model.work.InformationWork"%>
<%@page import="net.smartworks.util.SmartUtil"%>
<%@page import="net.smartworks.model.community.User"%>
<%@page language="java" contentType="application/vnd.ms-excel; name='excel', text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ page import="net.smartworks.service.ISmartWorks"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>

<%
	ISmartWorks smartWorks = (ISmartWorks) request.getAttribute("smartWorks");
	User cUser = SmartUtil.getCurrentUser();
	
	String workId = request.getParameter("workId");
	InformationWork work = (InformationWork) smartWorks.getWorkById(workId);

	response.setHeader("Content-Disposition", "attachment; filename=smartworks-data-template.xls"); 
	response.setHeader("Content-Description", "Template file generated By SmartWorks.net to be used to import data");
%>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>td.text {mso-number-format:\@}</style>       		
	</head>
	<body>
		<table style="width:100%;cellpadding:0; cellspacing; 0;" id="<%=work.getId()%>" name="<%=work.getName()%>">
			<thead>
				<tr>
				
					<th	style="border-collapse:collapse; border-spacing:0; border:1px solid #c7c7c7; background-color:#d8d8d8;width:20px">NO</th>					
					<%
					FormField[] importFields = work.getForm().getImportFields();
					if(!SmartUtil.isBlankObject(importFields)){
						for(int i=0; i<importFields.length; i++){
							FormField field = importFields[i];
							String type = field.getType();
							String nameDesc = "";
							if(type.equals(FormField.TYPE_DATE)) nameDesc = "yyyy.mm.dd";
							else if(type.equals(FormField.TYPE_DATETIME)) nameDesc = "yyyy.mm.dd hh:mm";
							else if(type.equals(FormField.TYPE_TIME)) nameDesc = "hh:mm";
							
					%>
							<th	id="<%=field.getId()%>" style="background-color:#d8d8d8; border-collapse:collapse; border-spacing:0; border:1px solid #c7c7c7;"><%=field.getName()%><%if(!SmartUtil.isBlankObject(nameDesc)){%><br/><%=nameDesc%><%}%></th>
					<%
						}
					}
					%>
				</tr>
				<%
				for(int j=0; j<100; j++){
				%>
					<tr>
						<td style="border-collapse:collapse; border-spacing:0; border:1px dotted #c7c7c7;text-align:center;width:30px"><%=j+1%></td>
						<%
						if(!SmartUtil.isBlankObject(importFields)){
							String msgFormat = null;
							for(int i=0; i<importFields.length; i++){
								FormField field = importFields[i];
								String type = field.getType();
								if(type.equals(FormField.TYPE_DATE)) field.setMandatory(true);
								String mandatoryColor = (field.isMandatory()) ? "background-color:#fceaea" : "";
						%>
								<td	id="<%=field.getId()%>" style="border-collapse:collapse; border-spacing:0; border:1px dotted #c7c7c7;<%if(!SmartUtil.isBlankObject(field.getStyle())){%><%=field.getStyle()%>;<%}%><%=mandatoryColor%>"></td>
						<%
							}
						}
						%>
					</tr>
				<%
				}
				%>
			</thead>
		<tbody>
	</body>
</html>