<%@page import="net.smartworks.model.work.FormField"%>
<%@page import="net.smartworks.model.work.InformationWork"%>
<%@page import="net.smartworks.util.SmartUtil"%>
<%@page import="net.smartworks.model.community.User"%>
<%@page import="org.apache.poi.hssf.usermodel.HSSFSheet"%>
<%@page import="org.apache.poi.hssf.usermodel.HSSFWorkbook"%>
<%@page import=" org.apache.poi.hssf.usermodel.HSSFRow"%>
<%@page import=" org.apache.poi.hssf.usermodel.HSSFCell"%>
<%@page import="java.io.*" %>
<%@page import="java.util.*" %>
<%@page import="net.smartworks.service.ISmartWorks"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>

<%
	ISmartWorks smartWorks = (ISmartWorks) request.getAttribute("smartWorks");
	User cUser = SmartUtil.getCurrentUser();
	
	String workId = request.getParameter("workId");
	InformationWork work = (InformationWork) smartWorks.getWorkById(workId);

/* 	response.setHeader("Content-Disposition", "attachment; filename=smartworks-data-template.xls"); 
	response.setHeader("Content-Description", "Template file generated By SmartWorks.net to be used to import data");
 */ 	
	try{
		HSSFWorkbook hwb = new HSSFWorkbook();
		HSSFSheet sheet1 = hwb.createSheet("Sheet1");
		HSSFSheet sheet2 = hwb.createSheet("Sheet2");

		HSSFRow rowhead = sheet1.createRow((short)0);

		FormField[] fields = (work.getForm()!=null) ? work.getForm().getFields() : null;
		if(!SmartUtil.isBlankObject(fields)){
			for(int i=0; i<fields.length; i++){
				FormField field = fields[i];
				String type = field.getType();
				if(		type.equals(FormField.TYPE_DATA_GRID) 
					|| type.equals(FormField.TYPE_FILE) 
					|| type.equals(FormField.TYPE_IMAGE) 
					|| type.equals(FormField.TYPE_OTHER_WORK) 
					|| type.equals(FormField.TYPE_RICHTEXT_EDITOR)) continue;
		
				rowhead.createCell(i).setCellValue(field.getName());
			}
		}
		sheet1.setSelected(true);
		FileOutputStream fileOut = new FileOutputStream("\test-data-template.xls");
		hwb.write(fileOut);
		fileOut.close(); 		

	} catch ( Exception ex ) {
		System.out.println(ex);
	}

%>
